[package]
name = "wordterm"
version = "0.1.0"
edition = "2024"

[dependencies]
anstream = "0.6.19"
anstyle = "1.0.11"
datetime = "0.5.2"
reqwest = { version = "0.12.22", features = ["json", "charset", "blocking"] }
serde_json = "1.0.141"

[profile.release]
strip = true
opt-level = "s"